定义了一个自定义异常类MyException，以及两个抛出该异常的方法